MontealegreLuis/poo1

fizzbuzz.cpp

se me complico un poco pero espero que este bien mi actividad

termino la tarea 1

---

proceso-tareas.md

Espero que ahora si este bien n.n
Gracias.

Tarea de markdown

---

tarea1.md

Este es el bueno, Ejercicio de Markdown. Moises Soto Aguilar

Tarea markdown

---

ejercicio1calificacion.scala
tarea1.md

Ejercicio 1, parte 1 algoritmos. Moises Soto Aguilar

Ejercicio1 1

---

ejercicio1calificacion.scala
ejercicio1hospital.scala
tarea1.md

Ejercicio 1 parte 2, hospital. Moises Soto Aguilar

Ejercicio1 2

---

cali.scala
hospital.scala
prcentaje.scala
proceso-tareas.md

Alondritha

---

hospital.scala

Ejercicio2 1

---

ejercicio1calificacion.scala
ejercicio1hospital.scala
ejercicio1porcentaje.scala
tarea1.md

Ejercicio 1 parte 3, porcentaje. Moises Soto Aguilar

Ejercicio1 3

---

ejercicio1calificacion.scala
ejercicio1hospital.scala
ejercicio1porcentaje.scala
ejercicio2pieza.scala
ejercicio2salario.scala
tarea1.md

Ejercicio 2 parte 2, salarios. Moises Soto Aguilar

Ejercicio2 2

---

ejercicio1calificacion.scala
ejercicio1hospital.scala
ejercicio1porcentaje.scala
ejercicio2pieza.scala
ejercicio2salario.scala
ejercicio3bola.scala
ejercicio3jubilacion.scala
tarea1.md

Ejercicio 3 parte 1 y 2, Bolas y Jubilación. Moises Soto Aguilar.

Ejercicio 3

---

procesos.tareas.md

termino la tares de markdown

---

bolitadescuento.scala
fabrica.scala
hospital.scala
jubilaciones.scala
salariotrabajador.scala

El que faltaba en los ejercicios 1

Ejercicios 1 2

---

atleta.scala
destienda.scala
edad.scala

los dos ejercicios de la tarea 3

ejercicios 3

---

tarea3_1.scala

Termino la tarea 3_1

---

piezasfabrica.scala
salario.scala

Ejercicios02correc

---

bolitadesc.scala
jubilaciones.scala
piezasfabrica.scala
salario.scala

Se los envio de nuevo ya compilan ambos, gracias.

Ejercicios3

---

Jubilados.scala

El codigo ya compila correctamente y cambie la sintaxis

Hice la correccion de sintaxis y ya compila

---

Hospital.scala
promedio.scala

ya compila el progrma, la sintaxis fue corregida

ya compila el progrma, la sintaxis fue corregida

---

Hospital.scala
fundacion.scala
promedio.scala
promedios.scala

los programas ya compilan correctamente

Practica 1

---

Markdown.md
fizzbuzz.scala

Practica fizzbuzz

---

Ejercicio 2.1.scala
Ejercicio 2.2.scala
MENU.scala
P1.1.scala
P1.2.scala
P1.3.scala
P3.1.scala
P3.2.scala
P4.1.scala
P4.2.scala
Proceso Cajero.scala
markdown-proceso_Tarea_4.md

Misael Albores Lopez - Ejercicios

POO1 [Corregido-Oficial™]

---

01_Ejercicio1.scala
01_Ejercicio2.scala
01_Ejercicio3.scala
02_Ejercicio1.scala
02_Ejercicio2.scala
03_Ejercicio1.scala
03_Ejercicio2.scala
04_Ejercicio1.scala
Cajero.scala
EjercicioFuncion.scala
Examen1.scala
Proceso-Tareas.md

Envio el ejercicio de la clase, funciones

EjercicioFuncion

---

ejercicio.scala
funciones.scala

Esta es la actividad con funciones

agrego ejercicio de funciones

---

funcion.scala
funciones.scala

resalizar un menu con funciones

tarea funciones

---

ejercicio4tiempo.scala
ejercicio4zoo.scala

Ejercicio 4. parte 1 y 2
Tempo de carrera 
Edad de animales de zoo

Tarde con la logica pero termine el Ejercicio 4

---

examen.scala
tarea5.scala
tarea7.scala
tarea7_1.scala

Tarea de los ejercicios del examen

Examen tarea

---

ejercicio4tiempo.scala
ejercicio4zoo.scala
ejercicio5funciones.scala

Termine la tarea 5 de funciones.

Ejercicio 5

---

catalogotiendaglobales.scala
ejercicio4tiempo.scala
ejercicio4zoo.scala
ejercicio5funciones.scala
examen1confunciones.scala

Catalo dela tienda con funciones, variables globales. Terminada y enviada y así.

Catalogo funcionesglob

---

examen.scala
funciones.scala

Aqui estan todos los ejercicios del examen

Ejercicios examen

---

catalogo.scala
examen.scala
funciones.scala

Ejerciciocatalogo

---

catalogo-no-globales.scala
noglobal.scala

esta es la actividad con la funcion de nota

agrego ejercicio de funciones con variables no globales

---

puntoscontaminantes.scala

primer ejercicio del examen de reposición

examen ejercicio 1

---

Calificacion.scala
Empresa.scala
Fabrica.scala
Funcion.scala
Hospital.scala
Jubilacion.scala
Prueba.scala
Salario.scala
Tienda.scala
Zoologico.scala

Ejercicio1

---

Calificacion.scala
Empresa.scala
Fabrica.scala
Funcion.scala
Hospital.scala
Jubilacion.scala
Prueba.scala
Salario.scala
Tienda.scala
Zoologico.scala

Arreglé los ejercicios 2.1 y 2.2

Ejercicio2

---

Calificacion.scala
Empresa.scala
Fabrica.scala
Funcion.scala
Hospital.scala
Jubilacion.scala
Prueba.scala
Salario.scala
Tienda.scala
Zoologico.scala

Arreglado los ejercicios 3.1 y 3.2

Ejercicio3

---

Calificacion.scala
Empresa.scala
Fabrica.scala
Funcion.scala
Hospital.scala
Jubilacion.scala
Prueba.scala
Salario.scala
Tienda.scala
Zoologico.scala

Arreglado el ejercicio 4.1 y 4.2

Ejercicio4

---

examen_1.scala

Termino la tarea de la resolución del examen.

Termino la tarea de la resolucion del examen

---

Calificacion.scala
Empresa.scala
Fabrica.scala
Funcion.scala
Hospital.scala
Jubilacion.scala
Prueba.scala
Salario.scala
Tienda.scala
Zoologico.scala

Terminado el ejercicio 1 y arreglado.

Ejer1 funcion

---

Calificacion.scala
Catalogo.scala
Empresa.scala
Examen.scala
Fabrica.scala
Funcion.scala
Hospital.scala
Jubilacion.scala
Prueba.scala
Salario.scala
Tienda.scala
Zoologico.scala

Terminado el ejercicio del catalogo.

Ejercicio catalogo

---

examen2arboles.scala
examen2auto.scala

Termino y envio el examen 2

---

examen_1.scala
funciones2.scala

Termino la tarea de funciones de los ejercicios #2

Funciones2

---

examen_1.scala
funciones2.scala
funciones3.scala

Termino la tarea de funciones, ejercicios numero 3

Funciones3

---

Examen2.scala

Termino el segundo examen

---

ejercicios2.scala

bloque 2 de ejercicios en funciones

Ejercicios2funciones

---

actividad1.scala
actividad2.scala
actividad3.scala

Profe hice estas actividades en funciones pero no pude quitar las variables globales... Se me dificulto

agrego actividades con funciones

---

actividad1.scala
actividad2.scala
actividad3.scala
clases.scala

Esta es la actividad con las operaciones

Operaciones

---

ejerciciofuncion2y3.scala

Funciones ejercicio 2 y 3

---

fraccion.scala

Termino la tarea de la fraccion

Termino la tarea de la fraccion

---

catalogo-no-globales.scala

Termino la tarea de la nota con parametros

Termino la tarea de la nota con parametros

---

Fracciones.scala
dividirfraccion.scala
fraccionmultiplicar.scala

se ha echo un cambio, ya he colocado un menú para acceder a las otras operaciones de las fracciones

Fracciones

---

TiendaClases.scala

esta es la actividad de la tienda con la clase Producto

Agrego ejercicio de la Tienda con  la clase producto

---

examen2.scala

perdone la demora lo q pasa es que mi git estaba fallando

parametros

---

Calificaciones.2.scala
Catalogo.scala
Expendio.4.scala
Numeros.1.scala
Reloj.3.scala

Profesor aquí están anexadas las tareas que me dijo no compilaban ya corregidas.

Tareas Corregidas

---

clasesTienda.scala

esta es la actividad de catalogo con la clase Catalogo

agrego actividad con la clase Catalogo

---

Examen2.scala
Funcion2.scala
Funcion3.scala

Terminado los ejercicios 2 y 3 con respectivas funciones.

Ejercicio 2 y 3

---

catalogoproducto.scala

Termino la tarea del catalogo

---

catalogo-clases.scala
clasesTienda.scala

Nota clase

---

NotaClase.scala
catalogo-clases.scala
catalogo.scala
clasesTienda.scala
nota.scala
producto.scala

profe esta es la actividad de nota con la funcion

Nota clase funcion

---

NotaClase.scala
catalogo-clases.scala
catalogo.scala
clasesTienda.scala
nota.scala
producto.scala
segundoExamen2.scala

profe este es el ejercicio del examen... Espero que este bien. Disculpe por la tardanza...

Examen segundo

---

catalogoclases.scala
cine.scala
examenes2.scala

Examencine

---

examen2Nomina.scala
examen2_peli.scala

agrego el examen de la Nomina :smiley:

examen2:pelicula

---

clase-catalogo.scala
clase_catalogo.scala

Clase catalogo

---

clase-catalogo.scala
clase_catalogo.scala
funcion-nota.scala
nota-clase.scala

Nota funcion

---

renta.scala

Termino la tarea de la renta de peliculas

Termino la tarea de la renta de peliculas

---

renta.scala

termino la tarea de la nomina de profesores

Termino la tarea de la nomina de profesores
